[project]
name = "energyanomalydetector"
version = "0.1.0"
requires-python = ">=3.11,<3.13"
dependencies = [
  "streamlit>=1.31,<2.0",
  "pandas",
  "numpy",
  "scikit-learn",
  "matplotlib",
  "altair==4.2.2"
]

